---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 'latest'

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
- name: debian-7.4.0
  driver_config:
    box: opscode-debian-7.4.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box

suites:
- name: default
  run_list:
  - recipe[eye_test]

